import type { Metadata } from 'next';
import StoreProvider from './StoreProvider';

import Sidebar from '@/components/sidebar/Sidebar';

import './globals.scss';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

interface IRootLayoutProps {
    children: React.ReactNode;
}

const RootLayout: React.FC<IRootLayoutProps> = ({ children }) => {
    return (
        <html lang="en">
            <head>
                <link
                    href="https://fonts.googleapis.com/icon?family=Material+Icons"
                    rel="stylesheet"
                />
            </head>
            <body>
                <StoreProvider>
                    <main className="main">
                        <Sidebar />
                        {children}
                    </main>
                </StoreProvider>
            </body>
        </html>
    );
};

export default RootLayout;
